### ISSUE TITLE
Too many ifs xD

### ISSUE THREAD

**Issue by crushr3sist** [archuser555/Pixel-Editor#1]
**repetition of tasks**
ofc I appreciate a wrapper for a library but this is kinda bordering on unreadable, also raylib is kinda a simplified wrapper for sfml

I would also recommend you use SDL so you have more control over the tasks you would like to accomplish with more of your personal touch.

**Comment by archuser555** [comment]
Ok, SDL2 kinda sucks, old and bad, 2013 nah, i think raylib are also suck :-), cuz it just opengl and opengl sucks, i think sfml? ok thank for this idea, sfml is better to manage, **not like opengl or sdl**, im gonna work to this now :-), i think.... im not too much good at sfml,pls try contribe and help me switch to sfml

**Comment by archuser555** [comment]
ima i forget to close this
